[project]
name = "bytebattles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.56",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "redis>=8.0.1",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "docker>=7.2.0",
    "fakeredis>=2.31.0",
    "httpx>=0.28.1",
    "httpx2>=1.0.0",
]
api = [
    "email-validator>=2.3.0",
    "fastapi>=0.140.0",
    "pwdlib[argon2]>=0.3.0",
    "pydantic>=2.13.4",
    "pyjwt>=2.13.0",
    "python-multipart>=0.0.32",
    "uvicorn>=0.51.0",
]
judge = [
    "docker>=7.2.0",
    "netifaces>=0.11.0",
]
